package ar.gob.itse.desafio.view;

import ar.gob.itse.desafio.controller.Universo;
import java.awt.BorderLayout;


public class JuegoAnimacion extends javax.swing.JFrame {

    
    private Universo universo;
    /**
     * Creates new form JuegoAnimacion
     */
    public JuegoAnimacion() {
        initComponents();
        
        //Centrar el JFrame en el centro de la pantalla
        this.setLocationRelativeTo(null);
        
                     
        this.universo = new Universo(this.pnlGeneral.getSize());
        this.pnlGeneral.add(this.universo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeneral = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniIniciar = new javax.swing.JMenuItem();
        mniDetener = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JuegoAnimacion");

        pnlGeneral.setBackground(new java.awt.Color(175, 232, 138));

        javax.swing.GroupLayout pnlGeneralLayout = new javax.swing.GroupLayout(pnlGeneral);
        pnlGeneral.setLayout(pnlGeneralLayout);
        pnlGeneralLayout.setHorizontalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        pnlGeneralLayout.setVerticalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        getContentPane().add(pnlGeneral, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mniSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Animación");

        mniIniciar.setText("Iniciar");
        mniIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniIniciarActionPerformed(evt);
            }
        });
        jMenu2.add(mniIniciar);

        mniDetener.setText("Detener");
        mniDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDetenerActionPerformed(evt);
            }
        });
        jMenu2.add(mniDetener);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        mniAbout.setText("About");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        jMenu3.add(mniAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniAboutActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniIniciarActionPerformed
        this.universo.animar(true);
        
    }//GEN-LAST:event_mniIniciarActionPerformed

    private void mniDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDetenerActionPerformed
        this.universo.animar(false);
    }//GEN-LAST:event_mniDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniDetener;
    private javax.swing.JMenuItem mniIniciar;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JPanel pnlGeneral;
    // End of variables declaration//GEN-END:variables
}
